name: Remove duplicate IPs

on:
  push:
    paths:
      - 'new.txt'
  workflow_dispatch:

jobs:
  remove-duplicates:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Memberikan izin untuk push
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Diperlukan untuk git history

      - name: Remove duplicate lines
        run: |
          cp new.txt ip_updated_backup.txt
          awk '!seen[$0]++' new.txt > ip_updated_unique.txt
          mv ip_updated_unique.txt ip_updated.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ip_updated.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Remove duplicate IPs"
          git push
