name: Merge Files - Remove Duplicates

on:
  workflow_dispatch:

jobs:
  merge-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Gabungkan dan hapus duplikat
      run: |
        # Gabungkan dua file, lalu hapus duplikat, simpan sebagai output.txt
        cat rawproxy.txt ProxyIsp.txt | sort -u > output.txt

        echo "✅ Hasil gabungan tanpa duplikat:"
        echo "-------------------------------"
        cat output.txt

    - name: Commit hasil
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output.txt
        git diff --quiet && git diff --cached --quiet || git commit -m "[Auto] Gabungkan file dan hapus duplikat"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
