name: Update Proxy IP Status

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # This is crucial for pushing changes

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}  # Important for write access

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update proxy status
      env:
        IP_FILE: 'ip.txt'
        API_URL: 'https://id1.foolvpn.me/api/v1/check?ip={ip}:{port}'
      run: |
        python update_proxy_status.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Check for changes
        git add -u
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Commit changes
        git commit -m "Update proxy IP status [$(date +'%Y-%m-%d')]"
        
        # Pull changes
        git pull origin main
        
        # Push changes
        git push origin HEAD:main
